-- MySQL Script generated by MySQL Workbench
-- Wed Mar  4 17:55:03 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema erp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema erp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS erp DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE erp ;

-- -----------------------------------------------------
-- Table erp.membre
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS erp.membre (
  id_membre INT NOT NULL AUTO_INCREMENT,
  nom VARCHAR(100) NOT NULL,
  prenom VARCHAR(100) NOT NULL,
  niveau_etude VARCHAR(50) NULL DEFAULT NULL,
  cellule VARCHAR(100) NULL DEFAULT NULL,
  montant_cotisation DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (id_membre))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table erp.cotisation
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS erp.cotisation (
  id_cotisation INT NOT NULL AUTO_INCREMENT,
  id_membre INT NOT NULL,
  date_paiement DATE NOT NULL,
  montant DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (id_cotisation),
  INDEX fk_cotisation_membre (id_membre ASC) VISIBLE,
  CONSTRAINT fk_cotisation_membre
    FOREIGN KEY (id_membre)
    REFERENCES erp.membre (id_membre)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table erp.evenement
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS erp.evenement (
  id_evenement INT NOT NULL AUTO_INCREMENT,
  nom VARCHAR(150) NOT NULL,
  date_prevue DATE NOT NULL,
  lieu VARCHAR(50) NULL DEFAULT NULL,
  statut VARCHAR(20) NULL DEFAULT NULL,
  categorie_activite VARCHAR(50) NULL DEFAULT NULL,
  budget_activite DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (id_evenement))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table erp.sponsor
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS erp.sponsor (
  id_sponsor INT NOT NULL AUTO_INCREMENT,
  nom_entreprise VARCHAR(150) NOT NULL,
  nom_responsable VARCHAR(50) NULL DEFAULT NULL,
  responsable_contact VARCHAR(150) NULL DEFAULT NULL,
  montant_accorde DECIMAL(10,2) NULL DEFAULT NULL,
  statut VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (id_sponsor))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table erp.sponsorisation
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS erp.sponsorisation (
  id_sponsor INT NOT NULL,
  id_evenement INT NOT NULL,
  PRIMARY KEY (id_sponsor, id_evenement),
  INDEX fk_spon_evenement (id_evenement ASC) VISIBLE,
  CONSTRAINT fk_spon_evenement
    FOREIGN KEY (id_evenement)
    REFERENCES erp.evenement (id_evenement)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_spon_sponsor
    FOREIGN KEY (id_sponsor)
    REFERENCES erp.sponsor (id_sponsor)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table erp.transaction_club
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS erp.transaction_club (
  id_transaction INT NOT NULL AUTO_INCREMENT,
  date_transaction DATE NOT NULL,
  montant DECIMAL(10,2) NOT NULL,
  type ENUM('income', 'expense') NOT NULL,
  description VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (id_transaction))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;